# render.yaml
services:
  - type: web
    name: hc-fastapi
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""  # 생략 가능
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: POSTGRES_USER
        value: myuser
      - key: POSTGRES_PASSWORD
        value: mypassword
      - key: POSTGRES_HOST
        value: db
      - key: POSTGRES_PORT
        value: 5432
      - key: POSTGRES_DB
        value: mydatabase
      - key: DATABASE_URL
        value: postgresql://myuser:mypassword@db:5432/mydatabase
