# render.yaml
services:
  - type: web
    name: hc-fastapi
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""  # 생략 가능
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: your_pw
      - key: POSTGRES_HOST
        value: your-db-host.render.com
      - key: POSTGRES_PORT
        value: 5432
      - key: POSTGRES_DB
        value: railway
      - key: DATABASE_URL
        value: postgresql://postgres:your_pw@your-db-host.render.com:5432/railway
