services:
  # FastAPI 웹 서비스 정의
  - type: web
    name: hc-fastapi
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: POSTGRES_USER
        value: myuser
      - key: POSTGRES_PASSWORD
        value: mypassword
      - key: POSTGRES_HOST
        fromDatabase:
          name: hc-postgres
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: hc-postgres
          property: port
      - key: POSTGRES_DB
        value: mydatabase
      - key: DATABASE_URL
        fromDatabase:
          name: hc-postgres
          property: connectionString

# PostgreSQL 데이터베이스 정의
databases:
  - name: hc-postgres
    plan: free
    databaseName: mydatabase
    user: myuser 